server:
  servlet:
    context-path: /api

spring:
  # H2 Database
  datasource:
    url: jdbc:h2:mem:tododb
    driverClassName: org.h2.Driver
    username: sa
    password:

  # JPA/Hibernate
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: false

  flyway:
    enabled: false

  # H2 Console
  h2:
    console:
      enabled: true
      path: /h2-console

  # SQL Init
  sql:
    init:
      mode: never

  # OAuth2
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "https://dev-pjwg2kitzxdg0b5x.us.auth0.com/"
          audiences: [ "https://todo-api" ]

logging:
  level:
    org.springframework.security: INFO