name: render ping
on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:
jobs:
  curl-website:
    runs-on: ubuntu-latest
    steps:
      - name: Run CURL on Website
        run: curl -v https://fullstack-todo-demo.onrender.com/api/health
